# Generated by Django 3.0.7 on 2020-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='managers',
            name='email',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='managers',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='managers',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
    ]
