# Generated by Django 3.0.7 on 2020-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200630_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='password',
            field=models.CharField(default='crowdstrike', max_length=100),
        ),
    ]
