# Generated by Django 3.0.7 on 2020-06-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type_choice',
            field=models.CharField(choices=[('S', 'Sales'), ('T', 'Technical'), ('C', 'Coaching'), ('O', 'Other')], default=0, max_length=1),
        ),
    ]
