# Generated by Django 3.0.7 on 2020-06-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_feedback_type_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Anonymous', max_length=60),
        ),
    ]
