# Generated by Django 3.0.7 on 2020-06-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_feedback_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='submitted_by',
        ),
    ]
