# Generated by Django 3.0.7 on 2020-06-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20200630_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type_choice',
            field=models.CharField(choices=[('S', 'Sales'), ('T', 'Technical'), ('C', 'Coaching'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
