# Generated by Django 3.0.7 on 2020-06-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20200630_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type_choice',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Technical', 'Technical'), ('Coaching', 'Coaching'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
