# Generated by Django 3.0.7 on 2020-07-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20200709_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Managers',
        ),
    ]
