# Generated by Django 3.0.7 on 2020-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20200713_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='salesforceOp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
