# Generated by Django 3.0.7 on 2020-07-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_feedback_salesforceop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='salesforceOp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
