# Generated by Django 3.0.7 on 2020-07-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20200715_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='manager',
        ),
    ]
